const td1El = document.createElement('td');
cartTable.appendChild(td1El);
td1El.textContent = "this.name";
const td2El = document.createElement('td');
cartTable.appendChild(td2El);
td2El.textContent = "this.name";
const td3El = document.createElement('td');
cartTable.appendChild(td3El);
td3El.textContent = "this.name";
const td4El = document.createElement('td');
cartTable.appendChild(td4El);
td4El.textContent = "this.name";